title: "AWS ParallelCluster ワークショップ"
summary: "AWS ParallelCluster の初学者向けワークショップです"
topics: ["Training", "ParallelCluster", "Distributed", "Slurm", "AWS"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 00-overview
  - aws-parallelcluster-workshop-01-getting-started
  - aws-parallelcluster-workshop-02-cluster
  - aws-parallelcluster-workshop-03-cpu-training
  - aws-parallelcluster-workshop-04-observability

