title: "Amazon EKS Distributed AI ワークショップ"
summary: "Amazon EKS を用いた分散 AI ワークショップ"
topics: ["EKS", "Terraform", "Karpenter", "GPU", "DistributedAI"]
published: true
chapters:
  - eks-overview
  - eks-vpc-foundation
  - eks-cpu-ddp
  - eks-karpenter-setup
  - eks-accelerator-pools
  - eks-capacity-block
  - eks-efa-topology
  - eks-run-workloads
  - eks-observability
  - eks-neuron-trainium-temp
  - eks-shared-storage
  - eks-teardown-and-options
    #  - eks-image-cache
    #  - eks-gdrcopy
    #  - eks-gpu-fault-injection
    #  - eks-tenant-pools
    #  - Kueue のセクションを追加したい
