title: "Model Context Protocol Security on AWS"
summary: "本書は文章作成に AI を利用していません。MCP の概要、考慮すべきセキュリティ、その対策方法、AWS を用いた実装まで踏み込んだ内容を丁寧に紹介します。"
topics: ["MCP", "AWS"]
published: false
price: 1000 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter01
  - chapter02
  - chapter03
